name: i_like_a_math
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scaffold_gradient_background: ^1.0.3+1
  flutter_bloc: ^8.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  audioplayers: ^1.0.1
  share_files_and_screenshot_widgets: ^1.0.6
  share_plus: ^4.2.0
  easy_localization: ^3.0.1
  get_it: ^7.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/app_icon/app_icon.png"


flutter:
  assets:
    - assets/langs/
    - assets/buttons/rate-it.png
    - assets/buttons/share-it.png
    - assets/buttons/arrow.png
    - assets/data/100-1000.dat
    - assets/sfx/snap_wavX.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Rabiohead
      fonts:
        - asset: assets/fonts/Rabiohead.ttf

